# Generated by Django 2.0.5 on 2018-05-25 05:54

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('live_charts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('fillColor', models.CharField(max_length=128)),
                ('strokeColor', models.CharField(max_length=128)),
                ('data', jsonfield.fields.JSONField(default={})),
            ],
        ),
        migrations.DeleteModel(
            name='Bar',
        ),
    ]
